<!--

    Copyright (C) Red Gate Software Ltd 2010-2024

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-parent</artifactId>
        <version>9.22.3</version>
        <relativePath/>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>flyway-community-db-support</artifactId>
    <packaging>pom</packaging>
    <version>9.22.3</version>
    <name>${project.artifactId}</name>

    <modules>
        <module>flyway-database-duckdb</module>
        <module>flyway-database-clickhouse</module>
        <module>flyway-database-opengauss</module>
    </modules>

    <properties>
        <version.flyway>9.22.3</version.flyway>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>flyway-core</artifactId>
                <version>${version.flyway}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.10</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>bundle-manifest</id>
                            <phase>process-classes</phase>
                            <goals>
                                <goal>manifest</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <repositories>
        <repository>
            <id>pscrepository</id>
            <name>pscrepository</name>
            <url>http://nexus.di-matrix.com/nexus/content/groups/public/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>maven-nexus-repository</id>
            <name>maven-nexus-repository</name>
            <url>http://nexus.di-matrix.com/nexus/content/repositories/thirdparty/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>aliyun-repos</id>
            <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>aliyun-plugin</id>
            <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>


    <!--使用分发上传将项目打成jar包，上传到nexus私服上-->
    <distributionManagement>
        <repository>
            <!--nexus服务器中用户名：在settings.xml中和<server>的id一致-->
            <id>maven-nexus-repository</id>
            <url>https://nexus.di-matrix.com/nexus/content/repositories/thirdparty</url>
        </repository>
        <snapshotRepository>
            <!--nexus服务器中用户名：在settings.xml中和<server>的id一致-->
            <id>maven-nexus-snapshots-repository</id>
            <url>https://nexus.di-matrix.com/nexus/content/repositories/snapshots</url>
        </snapshotRepository>
    </distributionManagement>

</project>
